### PR TITLE
Added blog.

### PR DESCRIPTION
**Pull request by jmssil**
Not sure this is the right way to do it.

### CODE REVIEW

**Comment by paulohva** [comment]
Hi @jmssil. Can you remove the `node_modules` directory from your PR? You can add it to your `.gitignore` file.

**Comment by jmssil** [comment]
Olá, Paulo @paulohva. I did that now and committed. I had forgotten to push (new to git) but I did that just now.

**Comment by paulohva** [comment]
> Olá, Paulo @paulohva. I did that now and committed. I had forgotten to push (new to git) but I did that just now.

Thanks @jmssil ! Can you remove just one more folder, please :)  `1-development/blog/tmp/`.

**Comment by jmssil** [comment]
Done @paulohva :)

**Pull request closed without merging**
